#!/usr/bin/env python

import game
import sys
import subprocess

U,P = sys.argv[1:3]

g=game.Galaxy()
g.login(U,P)
print 'Name, ID, Society, Population, Money, Food, Steel'
for p in g.planets:
  p.load()
  print '"%s", %d, %d, %d, %d, %d, %d' % (
    p.name, p.planetid, p.society, p.population, p.money, p.food[0], p.steel[0]
  )
  if p.can_build({'arcs': 1}):
    confirm = raw_input('"%s" can build an arc, execute? (y/N): ' % (p.name))
    if confirm == 'y':
      # TODO(cwren) translate the manifest above to json instead of recoding it:
      js = ('javascript:sendrequest(handleserverresponse, '
            '"/planets/%(id)d/buildfleet/", "POST", '
            '{"num-arcs": "1", '
            '"submit-build-%(id)d": 1, '
            '"submit-build-another-%(id)d": 1})') %  {'id': p.planetid}
      sys.stderr.write(js)
      # sys.stderr.write('\n')
      subprocess.call(['osascript', 'EvalJavascript.scpt', js ]);


