#!/usr/bin/python

import game
import sys

U,P,planetid=sys.argv[1:4]
tobuild=sys.argv[4:]

# TODO(cwren) make these flags
interactive = True
skip_check = False

g=game.Galaxy()
g.login(U,P)

manifest = {}
for pr in tobuild:
  ship, qty = pr.split("=")
  if ship in game.ALL_SHIPS.keys():
    if ship in manifest:
      manifest[ship] += int(qty)
    else:
      manifest[ship] = int(qty)
  else:
    print "error: unknown ship type: " + ship
    sys.exit(1)

planet = g.get_planet(int(planetid))

if not planet:
    print "error: unknown planet: " + planetid
    sys.exit(1)

if skip_check or planet.can_build(manifest):
  planet.build_fleet(manifest, interactive=interactive, skip_check=False)
else:
    print "error: planet cannot afford that fleet"
