#!/usr/bin/env python

import game
import sys
import subprocess

U,P = sys.argv[1:3]

def default_input(prompt, default):
  response = raw_input(prompt)
  if response == '':
    return default
  return response.lower()

escorted = {'arcs': 1, 'frigates': 1}
solo = {'arcs': 1}

SOLO_PROMPT = 'build solo arc at "%s"? (Y/v/n): '
ESCORTED_PROMPT = 'build escorted arc at "%s"? (Y/v/n): '

g=game.Galaxy()
g.login(U,P)
print 'Name, ID, Society, Population, Money, Food, Steel'
for p in g.planets:
  try:
    p.load()
    print '"%s", %d, %d, %d, %d, %d, %d' % (
      p.name, p.planetid, p.society, p.population, p.money, p.food[0], p.steel[0]
    )
    confirm = 'y'
    while confirm == 'y' and p.can_build(solo):
      if p.can_build(escorted):
        confirm = default_input(ESCORTED_PROMPT % (p.name), 'y')
        if confirm == 'y':
          p.build_fleet(escorted, interactive=True)
        elif confirm == 'v':
          p.view()
          confirm = 'y'
      else:
        confirm = default_input(SOLO_PROMPT % (p.name), 'y')
        if confirm == 'y':
          p.build_fleet(solo, interactive=True)
        elif confirm == 'v':
          p.view()
          confirm = 'y'
  except ValueError:
    print "failed to laod %s" % p.name
