#!/usr/bin/env python

import game
from optparse import OptionParser
import sys
import types

parser = OptionParser()
parser.add_option("-U", "--username", dest="username",
                  help="username of login")
parser.add_option("-P", "--password", dest="password",
                  help="password for login")
(options, args) = parser.parse_args()

g=game.Galaxy()
if options.username and options.password:
  # explicit login
  g.login(options.username, options.password, force=True)
else:
  # try to pick up stored credentials
  g.login()

def dictstr(d):
  return "(" + " ".join(
    "%s=%s" % (str(k),str(v)) for (k,v) in d.items()) + ")"

print 'ID, Disposition, Coords, Destination, Ships'
for f in g.fleets:
  f.load()
  dest = f.destination
  if type(dest) in (types.ListType, types.TupleType):
    dest = '(%.1f,%.1f)' % tuple(dest)
  else:
    dest = str(dest)
  print '%d %s (%.1f,%.1f)-->%s %s' % (
    f.fleetid, f.disposition, 
    f.coords[0], f.coords[1],
    dest,
    dictstr(f.ships)
  )


