#!/usr/bin/env python

import game
from optparse import OptionParser
import sys

parser = OptionParser()
parser.add_option("-U", "--username", dest="username",
                  help="username of login")
parser.add_option("-P", "--password", dest="password",
                  help="password for login")
(options, args) = parser.parse_args()

g=game.Galaxy()
if options.username and options.password:
  # explicit login
  g.login(options.username, options.password, force=True)
else:
  # try to pick up stored credentials
  g.login()

print 'Name, ID, Society, Population, Money, Food, Steel, Tax, Tarif, Distance'
for p in g.planets:
  p.load()
  print '"%s", %d, %d, %d, %d, %d, %d, %.1f, %.1f, %.1f' % (
    p.name, p.planetid, p.society, p.population, 
    p.money, p.food[0], p.steel[0], p.tax, p.tarif, p.distance
    )
  for idx, status in enumerate(p.upgrades):
    if status == game.UPGRADE_AVAILABLE:
      print "\tcan build %s" % game.UPGRADES[idx]
    elif status > game.UPGRADE_AVAILABLE:
      print "\thas %s" % game.UPGRADES[idx]
g.write_planet_cache()

