#!/usr/bin/env python
# vim: set ts=2 sw=2 expandtab:

import game
from optparse import OptionParser
import sys
import shape

def main():
  parser = OptionParser()
  parser.add_option("-U", "--username", dest="username",
                    help="username of login")
  parser.add_option("-P", "--password", dest="password",
                    help="password for login")
  parser.add_option("-n", "--noupgrade", dest="doupgrade",
                    action="store_false", default=True, help="dry run")
  parser.add_option("-s", "--source_route", dest="source",
                    type="string", help="source route area")
  parser.add_option("-d", "--dest_route", dest="dest",
                    type="string", help="destination route area")

  (options, args) = parser.parse_args()

  print "options " + str(options)

  g=game.Galaxy()
  if options.username and options.password:
    # explicit login
    g.login(options.username, options.password, force=True)
  else:
    # try to pick up stored credentials
    g.login()

  try:
    dest_route = g.find_route(options.dest)
    dest_shape = shape.Polygon(*(dest_route.points))
  except:
    print "could't find dest route"
    sys.exit(1)

  source_shape = None
  try:
    source_route = g.find_route(options.source)
    source_shape = shape.Polygon(*(source_route.points))
  except:
    pass

  g.load_fleet_cache()

  if source_shape == None:
    print "could't find source route"
    sys.exit(1)

  RedirArcsFromOwned(g, options.doupgrade, dest_shape)
  RedirReturningArcs(g, options.doupgrade, source_shape, dest_shape)

#  RedirArcsFromSource(g, options.doupgrade, source_shape, dest_shape)

  g.write_fleet_cache()

# redirect all arcs with targets in source shape into dest shape
def RedirArcsFromSource(g, doupgrade, source_shape, dest_shape):

  print "finding planets in source sector..."
  source_targets = FindAllPlanetsInShape(g, source_shape)
  print "%d planets in source sector" % len(source_targets)

  print "finding planets in target sector..."
  targets = FindUnownedPlanetsInShape(g, dest_shape)
  print "%d unowned planets in target sector" % len(targets)

  print "removing overlap planets from source..."
  for p in targets:
    for s in source_targets:
      if p.planetid == s.planetid:
        targets.remove(p)

  print "%d unowned planets in target sector" % len(targets)

  print "removing already targetted planets in target sector..."
  targets = TrimColonyTargettedPlanets(g, targets)
  print "%d unowned planets in target sector" % len(targets)

  if len(targets) == 0:
    print "all planets in destination already claimed"
    return False

  redir_arcs = []
  for f in g.fleets:
    f.load()
    try:
      if f.ships['arcs'] == 1:
        #print "found potential arc fleet %s, destination %s" % (f, f.destination)

        dest_planet_id = FleetDestToPlanetID(f.destination)

        for p in source_targets:
          if int(p.planetid) == int(dest_planet_id):
            print "found arc %s heading into source space" % f

            redir_arcs.append(f)
            break
    except:
      pass


  print "%d arcs to redirect from source" % len(redir_arcs)

  RedirArcs(g, doupgrade, redir_arcs, targets)

# redirect arcs with their home as their target
def RedirReturningArcs(g, doupgrade, source_shape, dest_shape):

  targets = FindUnownedPlanetsInShape(g, dest_shape)
  owned_planets = FindOwnedPlanetsInShape(g, dest_shape)

  print "%d unowned planets in sector" % len(targets)

  targets = TrimColonyTargettedPlanets(g, targets)
  print "%d unowned planets in sector after trimming colony targets" % len(targets)

  if len(targets) == 0:
    print "all planets in destination already claimed"
    return False

  redir_arcs = []
  for f in g.fleets:
    f.load()
    if f.ships.get('arcs', 0) > 0:
      #print "found potential arc fleet %s, destination %s" % (f, f.destination)

      dest_planet_id = FleetDestToPlanetID(f.destination)

      #print "fleet %s dest %s home %s" % (f, str(dest_planet_id), str(f.home.planetid))

      if source_shape == None or source_shape.inside(f.coords):
        if dest_planet_id == f.home.planetid:
          print "found returning arc %s" % f

          redir_arcs.append(f)

  RedirArcs(g, doupgrade, redir_arcs, targets)

# redirect arcs away from owned planets
def RedirArcsFromOwned(g, doupgrade, dest_shape):

  targets = FindUnownedPlanetsInShape(g, dest_shape)
  owned_planets = FindOwnedPlanetsInShape(g, dest_shape)

  print "%d unowned planets in sector" % len(targets)

  targets = TrimColonyTargettedPlanets(g, targets)
  print "%d unowned planets in sector after trimming colony targets" % len(targets)

  if len(targets) == 0:
    print "all planets in destination already claimed"
    return False

  redir_arcs = []
  for f in g.fleets:
    f.load()
    try:
      if f.ships['arcs'] == 1:
        #print "found potential arc fleet %s, destination %s" % (f, f.destination)

        dest_planet_id = FleetDestToPlanetID(f.destination)

        for p in owned_planets:
          if int(p.planetid) == int(dest_planet_id):
            print "found newly owned planet %s with arc %s heading for it" % (p, f)

            redir_arcs.append(f)
            break
    except:
      pass

  RedirArcs(g, doupgrade, redir_arcs, targets)

def RedirArcs(g, doupgrade, arc_fleets, targets):
  print "redirecting %d arcs to %d targets" % (len(arc_fleets), len(targets))

  # sort the shortest distances for each fleet
  for f in arc_fleets:
    f.targets = sorted(targets, key=lambda planet: game.distance_between(f.coords, planet.location))

  # iterate over all the fleets, building the shortest route of all of them
  while len(arc_fleets) > 0 and len(targets) > 0:
    # sort all of the remaining arcs by their shortest route
    arc_fleets = sorted(arc_fleets, key=lambda fleet: game.distance_between(fleet.coords, fleet.targets[0].location))

    arc = arc_fleets[0]
    target = arc.targets[0]
    print "moving fleet %s to planet %s, distance %f" % (arc, target, game.distance_between(arc.coords, target.location))
    if doupgrade:
      arc.move_to_planet(target)

    # remove this fleet and this target out of all of the lists
    arc_fleets.remove(arc)
    for f in arc_fleets:
      f.targets.remove(target)

    # trim the master target list
    targets.remove(target)

  for f in arc_fleets:
    del f.targets

def FindUnownedPlanetsInShape(g, shape):
  sect = g.load_sectors(shape.bounding_box())

  planets = []
  for p in sect["planets"]["unowned"]:
    if shape.inside(p.location):
      planets.append(p)

  return planets

def FindOwnedPlanetsInShape(g, shape):
  sect = g.load_sectors(shape.bounding_box())

  planets = []
  for p in sect["planets"]["owned"]:
    if shape.inside(p.location):
      planets.append(p)

  return planets

def FindAllPlanetsInShape(g, shape):
  sect = g.load_sectors(shape.bounding_box())

  planets = []
  for p in sect["planets"]["owned"]:
    if shape.inside(p.location):
      planets.append(p)
  for p in sect["planets"]["unowned"]:
    if shape.inside(p.location):
      planets.append(p)

  return planets

def TrimColonyTargettedPlanets(g, targets):
  # trim the list of targets to ones that dont have an arc already incoming
  for f in g.fleets:
    f.load()
    try:
      if f.disposition == "Colonize":
      # look for destinations in the NAME-NUMBER form
        pnum = int(f.destination.split('-')[1])
        for p in targets:
          if p.planetid == pnum:
            #print "fleet " + str(f) + " already heading for dest"
            targets.remove(p)
            break
    except:
      pass

  return targets

def FleetDestToPlanetID(destination):
  # if it's a real planet target, get the id
  dest_planet_id = None
  try:
    dest_planet_id = int(destination.planetid)
  except:
    pass

  # if its a string target, try to extract the planetid from it
  if dest_planet_id == None:
    try:
      s = destination.split('-')
      dest_planet_id = int(s[len(s)-1])
    except:
      pass

  return dest_planet_id

if __name__ == "__main__":
    main()
