#!/usr/bin/env python

import game
from optparse import OptionParser
import sys

parser = OptionParser()
parser.add_option("-U", "--username", dest="username",
                  help="username of login")
parser.add_option("-P", "--password", dest="password",
                  help="password for login")
(options, args) = parser.parse_args()

fleetid = args[0]

g = game.Galaxy()

if options.username and options.password:
  # explicit login
  g.login(options.username, options.password, force=True)
else:
  # try to pick up stored credentials
  g.login()

fleet = game.Fleet(g, int(fleetid), [0.0, 0.0], True)
fleet.scrap()
