#!/usr/bin/env python
# vim: set ts=2 sw=2 expandtab:

import game
from optparse import OptionParser
import sys
import shape

def main():
  parser = OptionParser()
  parser.add_option("-U", "--username", dest="username",
                    help="username of login")
  parser.add_option("-P", "--password", dest="password",
                    help="password for login")
  parser.add_option("-n", "--noupgrade", dest="doupgrade",
                    action="store_false", default=True, help="dry run")
  parser.add_option("-d", "--disposition", dest="disposition",
                    type="string", default="", help="only for fleets with this disposition")

  (options, args) = parser.parse_args()

  print "options " + str(options)

  g=game.Galaxy()
  if options.username and options.password:
    # explicit login
    g.login(options.username, options.password, force=True)
  else:
    # try to pick up stored credentials
    g.login()

  ScrapHome(g, options.doupgrade, options.disposition)

def ScrapHome(g, doupgrade, disposition=""):
  g.load_fleet_cache()

  for f in g.fleets:
    f.load()
    #print f.at_planet
    #print f.home
    #print f.destination
    if f.at(f.home) and f.destination == f.home:
      if disposition == "" or f.disposition == disposition:
        print "fleet %s is at home" % f
        if doupgrade:
          success = f.scrap()
  
  g.write_fleet_cache()

if __name__ == "__main__":
    main()
